import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import './page.css'


const inter = Lato({
  subsets: ['latin'],
  weight: '300'
})

export const metadata: Metadata = {
  icons: '/favicon.ico',
  title: 'Clinica Audmed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
