export interface Metadata {
    icons: "/favicon.ico"; // Adicione o caminho correto para o ícone, por exemplo, "/favicon.ico"
    title: string;
    description: string;
  }
  
  export const metadata: Metadata = {
    icons: '/favicon.ico',
    title: 'Clinica Audmed',
    description: 'Generated by create next app',
  };